name: Build and deploy Node.js app to Azure Web App - DigiSCA

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: backend-scada
        run: npm install

      - name: Build app (optional)
        working-directory: backend-scada
        run: npm run build --if-present

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "DigiSCA"
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./backend-scada

        id: deploy-to-webapp
        with:
          app-name: 'DigiSCA'
          slot-name: 'Production'
          package: .

          
